# Generated by Django 3.0.3 on 2020-11-21 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('risk_analysis', '0002_auto_20201121_1112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domains',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='risk_analysis.BaseModel')),
                ('name', models.CharField(db_column='DOMAIN', max_length=100)),
                ('point', models.FloatField(db_column='POINT', default=0.0, help_text='Set your domain point of your variable', max_length=100)),
            ],
            options={
                'db_table': 'DOMAINS',
            },
            bases=('risk_analysis.basemodel',),
        ),
        migrations.CreateModel(
            name='Subtypes',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='risk_analysis.BaseModel')),
                ('pts', models.FloatField(db_column='PTS', help_text='Point of specified intervals of your subtype related Domain', max_length=100)),
                ('min_interval', models.FloatField(db_column='MIN_INTERVAL', help_text='Minimum interval', max_length=100)),
                ('max_interval', models.FloatField(db_column='MAX_INTERVAL', help_text='Maximum interval', max_length=100)),
                ('domain_name', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.PROTECT, to='appconfig.Domains')),
            ],
            options={
                'db_table': 'SUBTYPES',
            },
            bases=('risk_analysis.basemodel',),
        ),
    ]
