# Generated by Django 3.0.5 on 2020-08-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkaccount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkaccount',
            name='taxpayer_number',
            field=models.CharField(db_column='TAXPAYER_NUMBER', help_text='Sahis firmasi ise TCKNO, Tuzel Kisilik iseVergi No', max_length=15, unique=True),
        ),
    ]
